# This is a basic workflow to help you get started with Actions

name: Czech
# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Remove
        run: |
          sudo rm -rf /opt/hostedtoolcache/ /imagegeneration /usr/local/.ghcup/ /usr/share/swift
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 3072
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
          build-mount-path: '/'
          pv-loop-path: '/mnt/pv.img'
      #- name: Get Largest
      #  run: |
      #    du -a / | sort -n -r | head -n 40
      - name: Check free space
        run: |
          echo "Free space:"
          df -h
      - uses: actions/checkout@v4
      - name: Get Level 1 map
        run: |
          sudo apt update
          sudo apt purge firefox
          sudo apt upgrade
          sudo apt install screen locate libapache2-mod-tile renderd git tar unzip wget bzip2 apache2 lua5.1 mapnik-utils python3-mapnik python3-psycopg2 python3-yaml gdal-bin npm fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted fonts-unifont fonts-hanazono postgresql postgresql-contrib postgis postgresql-14-postgis-3 postgresql-14-postgis-3-scripts osm2pgsql net-tools curl
          ls -l
          sudo usermod -aG sudo postgres
          sudo systemctl start postgresql
          sudo chmod 777 -R .
          sudo -u postgres pwd
          sudo -u postgres ls -l
          chmod +x createdb.sh
          sudo su -c "echo \"postgres ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers"
          sudo -u postgres ./createdb.sh
