# This is a basic workflow to help you get started with Actions

name: Czech
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-android: 'true'
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Remove
        run: |
          sudo rm -rf /opt/hostedtoolcache/
          sudo rm -rf /imagegeneration
      - name: Get Largest
        run: |
          du -a / | sort -n -r | head -n 40
      - name: Check free space
        run: |
          echo "Free space:"
          df -h
     # - name: Get Level 1 map
     #   run: |
     #     sudo apt update
     #     sudo apt purge firefox
     #     sudo apt upgrade
     #     sudo apt install screen locate libapache2-mod-tile renderd git tar unzip wget bzip2 apache2 lua5.1 mapnik-utils python3-mapnik python3-psycopg2 python3-yaml gdal-bin npm fonts-noto-cjk fonts-noto-hinted fonts-noto-unhinted fonts-unifont fonts-hanazono postgresql postgresql-contrib postgis postgresql-14-postgis-3 postgresql-14-postgis-3-scripts osm2pgsql net-tools curl
     #     ls -l
          #sudo -u postgres -i
          #createuser _renderd
          #createdb -E UTF8 -O _renderd gis

